language: python
sudo: false
python:
  - "3.4.3"

install:
  - pip install -U twine
  - make install
  - ./env/bin/pip install coveralls

script:
  - make checkstyle
  - make test

after_success:
  - ./env/bin/coveralls

deploy:
- provider: pypi
  user: marvinpinto
  password:
    secure: "peb6WWe28Iw/RRAAC1jVMlNcemvfc9qPnr+lQefdnCWLSkeO0Ame3m1kGxMmPYCosUHY77BVJnoxiGX2BxgAGeQoy65B1DdP/ayv8RoXSCgqalLrWM32PjVwPENE54tkn0+F5rHmyco4QvLO6byIwY1jOMSWTRkaihvJKwJeGdXMA0684DHWfVQK26DnUnLnohKeeT9Wf6AXCWHMFPaaK0on0FHcirQaLbi0RlYOPOsiZoA/p3fyYIJmVYfnEjIfY5JljbXlSh+AO+FNGKGLWJPlUqnS0rI9altu1xz8Wc8t4Ju9w1U1ozo7KlmHDubPtCmWLf982+GVwvoFfhx2ZfekcLSEMtCr8sNPhff7wid0hKJ+s8j4k+MFWMH8yWTHJ1kMhOJJZy5Q3gwyjoYrrQsQTU5DofdMZCvTGkeEGw6CCwCiH6/eKCPvBLi73n/w6a6Z/3kd8IT4yFvvp0JlLnMpKm2xADk28ReOmDVoogxw8LiGV4eZXAV1QsRR5Q0j3byBfK8Qe0xcQMqba9Hqn08hUmRwbwt/e+UKHilWoaEdeQzio0udEJ4cyi3/4q6S/YnNm/yE5Rk8B3t3cLe1xyKAtICoj78xlNemAI9xIq81wfo6ODve/TGZTFpZryjg0iAmB0P7SoJlS0m6PpYkXdzFLzWzTrKjFdRF92H8uWk="
  on:
    tags: true
    repo: marvinpinto/charlesbot-rundeck

notifications:
  email: false
  irc:
    - secure: "E8Z3XamIcwDs0PLHKN1IQIpA28aCMsHq7nUY5ZQP85h4JoQriXJGUvniHnr+qv4odqTyC+B4CnN2jnEQldjf2lDqSwEF7l/xFIqE2uDtLWOke2mcty8Geznlk0jRsxtwSB8aIvSp9GP5GU4iXzX+S6Sgl9LuDhVXjeqXR3xL6yH1dBaAqCo50QKWH1NO1JtROnGFm++cjo5saSvmt5oUILPKJnx/dWawEo2d0+cyBiuCmwAyhWT1qyTFuVnJIzF0Q70sA7HbFbcm0BXcZfhSVEOOgd/DMwOYRg6oP3lj+M1kdHDMpt5+iKXQ9C9Z/EueW++vNA18anC37C0brasXYIXhx/MfkSS/0UXzouLKpClZ5j9rgwEFc1VTdoKhnmXnfNtZPuhgvgTtsyyfjmVzuyoYtQ8bHGfbeKMMy3yY0L0BP5NzGJMSo2JIHVzvsDxk9moTVzyShvSJ4M9fjTEfn3i4aOeNjJ8beMsVmYKNDOGsFSYcMx6wKZd6jLaQbXXMArihLaSpoEbPUrE/28csMC7Vr5s8Xv/vWjXmeXTA4SPJReS/q1FPW3P3sqmJ+i+gl2kW25k+8TLVYfqch8jObzrbxgh6qGFZgXp7YueaAH98DfwlLmnk/HgJDK7jh8/ScNMR9lYa3rLJpJlxG1ZdndMoF/PZVkGhFPSVZvnSHNU="
