language: python
sudo: false
python:
  - "3.4"

install:
  - pip install -U twine
  - make install
  - ./env/bin/pip install coveralls

script:
  - make checkstyle
  - make test

after_success:
  - ./env/bin/coveralls

deploy:
- provider: pypi
  user: marvinpinto
  password:
    secure: "peb6WWe28Iw/RRAAC1jVMlNcemvfc9qPnr+lQefdnCWLSkeO0Ame3m1kGxMmPYCosUHY77BVJnoxiGX2BxgAGeQoy65B1DdP/ayv8RoXSCgqalLrWM32PjVwPENE54tkn0+F5rHmyco4QvLO6byIwY1jOMSWTRkaihvJKwJeGdXMA0684DHWfVQK26DnUnLnohKeeT9Wf6AXCWHMFPaaK0on0FHcirQaLbi0RlYOPOsiZoA/p3fyYIJmVYfnEjIfY5JljbXlSh+AO+FNGKGLWJPlUqnS0rI9altu1xz8Wc8t4Ju9w1U1ozo7KlmHDubPtCmWLf982+GVwvoFfhx2ZfekcLSEMtCr8sNPhff7wid0hKJ+s8j4k+MFWMH8yWTHJ1kMhOJJZy5Q3gwyjoYrrQsQTU5DofdMZCvTGkeEGw6CCwCiH6/eKCPvBLi73n/w6a6Z/3kd8IT4yFvvp0JlLnMpKm2xADk28ReOmDVoogxw8LiGV4eZXAV1QsRR5Q0j3byBfK8Qe0xcQMqba9Hqn08hUmRwbwt/e+UKHilWoaEdeQzio0udEJ4cyi3/4q6S/YnNm/yE5Rk8B3t3cLe1xyKAtICoj78xlNemAI9xIq81wfo6ODve/TGZTFpZryjg0iAmB0P7SoJlS0m6PpYkXdzFLzWzTrKjFdRF92H8uWk="
  on:
    tags: true
    repo: marvinpinto/charlesbot-rundeck

notifications:
  email: false
  irc:
    - secure: "azqoAHA9X0EtZ8rRgGxncEBP5UKF3/Xk7dVTNo/cAhiRWDix7HuY80MvQIK11gmBY44Dg53x8yaDFBi0T6ekR+EqsfCLWGXehmtQN0yKktMCbN0/wO8NjL4cYWvFZ/bK7EHhP28T3Cx5W65HAwMncU65+uVxCS6vi9Vz9swyZ+0N1nvk0jf1fB7eg2mCmEPmad9n4zk+RsMcJCS1r/kJyno53Fh2r0nM5snZGmzQyhBwB2egeSDE9krWycWXgyOxO6/NF0gx6wT4Qk8tH+bVSFCYPDcxQGGhKEFtWDNEc01gXHPyBAN8x5H30EKV1lRpw4USVDo1AoztsT0yNxWl0Eb57VqTj0IL/3oMpofGBENVecOTwMJOEAj0yBJambnyCy/jacE/Hk2f7eUr7L9Dci6A6zd2yMrG1sGYMu+tLTlOwBFyW3EyjWRLfAywXznaQh8xQBtX1i9mV4exF4zyBsp46+pDxPJX5oY7KyHsbkaOqx178b+KO3XezoFT8AyckX4Iuksx0Mp+4mgQ6eDeOwoOWkWdWUJvvzODXGpxgIqTUo58NjdabjHbxyEA/WumyGnx+UM/f8K3zmqz3wMYXtR3Y28vpqIyaesnhf87ZW+GsWfLANhRxtTfWCnWcr3TN1OHvLAYD/1/l1NtQYk3xHK+bkIQCptdOBAER4nSYVM="
